version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: '*'
        update-types:
          ['version-update:semver-minor', 'version-update:semver-patch']
    open-pull-requests-limit: 10
    versioning-strategy: increase
