version: '3.9'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ./public:/var/www/html/wp-content/themes/project-name
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

volumes:
  db_data: {}
  wordpress_data: {}
